### ISSUE TITLE
Syntax Error : newline

### ISSUE THREAD

**Issue by ecomdata** [monitoringplugins/check_pve_zsync#1]
I get this error anytime I try to run with good permissions. I tried it on 15 debian Server. Its not just me a few of my college tested and have the same problem. Somewhere in the code there is a mistake. Can you please solve that? That is the only zsync check out and it looks great.

Thank you :)

**Comment by itnjd** [comment]
Ok. I take a look at it later.

**Comment by ecomdata** [comment]
Thats also an option if you can translate to other language, and dont need to waiste time with GO things, i cannot do that, also as I see nobody can. or a setup video would be helpful. Many Thanks. Its really important to me.

**Comment by jabdr** [comment]
I guess you tried to run the source file, instead of the binary. Please use the binary from the releases page or build it with the go compiler (see readme).
